id = "ion"
name = "Ion"
description = "Amazon Ion and Ion Schema Language support."
version = "0.1.1"
schema_version = 1
authors = ["Riccardo Strina <riccardo.strina@icloud.com>"]
repository = "https://github.com/tartarughina/zed-amazon-ion"

[grammars.ion]
repository = "https://github.com/tartarughina/tree-sitter-ion"
commit = "98f399982252649eca1e74c684aa828763579f58"

[grammars.ion_schema]
repository = "https://github.com/tartarughina/tree-sitter-ion-schema"
commit = "c3d200c9355d0d0cd93c507eea1b2668ec19d793"
