name = "ion_schema"
grammar = "ion_schema"
path_suffixes = ["isl"]
line_comments = ["// "]
block_comment = ["/*", "*/"]
autoclose_before = ";:.,=}])"
brackets = [
    { start = "{", end = "}", close = true, newline = true },
    { start = "[", end = "]", close = true, newline = true },
    { start = "(", end = ")", close = true, newline = true },
]

# Add word characters for better selection
word_characters = ["-", "_", "$"]
